// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3r7onYNm2JV_XaQgE6wz0u1-LXbGZc9I',
    appId: '1:975411266137:web:7758d587e138062689e748',
    messagingSenderId: '975411266137',
    projectId: 'news-reader-app-fa3e4',
    authDomain: 'news-reader-app-fa3e4.firebaseapp.com',
    storageBucket: 'news-reader-app-fa3e4.firebasestorage.app',
    measurementId: 'G-2G8Z5JV3NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCshpWgrDnnSYRrLyrcU8yyscxQXZS8mOo',
    appId: '1:975411266137:android:4db009abcb5fd27989e748',
    messagingSenderId: '975411266137',
    projectId: 'news-reader-app-fa3e4',
    storageBucket: 'news-reader-app-fa3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTnzDOZQl97boKQiTJnrhNIU_icMNjSs',
    appId: '1:975411266137:ios:8975d3522b2afa9c89e748',
    messagingSenderId: '975411266137',
    projectId: 'news-reader-app-fa3e4',
    storageBucket: 'news-reader-app-fa3e4.firebasestorage.app',
    iosBundleId: 'com.example.newsreader.newsReaderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTnzDOZQl97boKQiTJnrhNIU_icMNjSs',
    appId: '1:975411266137:ios:8975d3522b2afa9c89e748',
    messagingSenderId: '975411266137',
    projectId: 'news-reader-app-fa3e4',
    storageBucket: 'news-reader-app-fa3e4.firebasestorage.app',
    iosBundleId: 'com.example.newsreader.newsReaderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3r7onYNm2JV_XaQgE6wz0u1-LXbGZc9I',
    appId: '1:975411266137:web:56d9220821ab5b9189e748',
    messagingSenderId: '975411266137',
    projectId: 'news-reader-app-fa3e4',
    authDomain: 'news-reader-app-fa3e4.firebaseapp.com',
    storageBucket: 'news-reader-app-fa3e4.firebasestorage.app',
    measurementId: 'G-LV54G1S5LD',
  );
}
